### ISSUE TITLE
Automatic export of proof terms

### ISSUE THREAD

**Issue by jaycech3n** [jaycech3n/Isabelle-HoTT#5]
Currently, we use `schematic_goal` to derive proof terms, then copy-paste the proof term in a new definition to be used in further proofs. It would be nice to automatically export derived proof terms, e.g.
```
schematic_goal my_lemma: "?prf: A"
proof
...
qed
```
should export the term derived by the schematic goal as `my_lemma_prf`.

**Comment by dan323** [comment]
You can define a new command to define proof terms as in isabelle/HOL they define types with typedef. In that case they set a goal "The type is not empty" and once it is proven, they define the type.

**Comment by jaycech3n** [comment]
That would be the idea, I just haven't got around to learning how to do that in Isabelle/ML yet. If you happened to know more it would be nice to work on this!

**Comment by jaycech3n** [comment]
Implemented in c2dfffffb7586662c67e44a2d255a1a97ab0398b.
